### ISSUE TITLE
Semantic DOM Feedback!

### ISSUE THREAD

**Issue by mfehrenbach** [jonamon5/manuscript#1]
- [x] Love the semantic thoroughness here. Not sure if `address` is quite right, maybe just `p` there? And would drop the `br`, [outside of poetry](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/br)!
https://github.com/jonamon5/manuscript/blob/7446b7b8b5420133c696fae02a4e7f66d4c6d2e3/index.html#L8-L15

- [ ] Would do this with a `span` [and some CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform): 
https://github.com/jonamon5/manuscript/blob/7446b7b8b5420133c696fae02a4e7f66d4c6d2e3/index.html#L23C9-L23C33

- [ ] No need to manually line break/rag/wrap like this—just let the paragraphs go long, and toggle visual wrapping in VS Code with `⌥` `Z`:
https://github.com/jonamon5/manuscript/blob/7446b7b8b5420133c696fae02a4e7f66d4c6d2e3/index.html#L23-L25

- [ ] Don’t think `code` is right here? If you want to keep the `—` separate from the text style, could consider [a `::before`](https://typography-interaction-2425.github.io/topic/css/#pseudo-elements):
https://github.com/jonamon5/manuscript/blob/7446b7b8b5420133c696fae02a4e7f66d4c6d2e3/index.html#L63

Overall, great start! Clear, consistent hierarchy and fundamentals. I think now I might suggest enriching this with some links and more design-y elements (manually selecting some pull quotes as `blockquote`, for example) to give yourself more stylistic material to work with!

✊

**Comment by jonamon5** [comment]
Hey Michael, thanks for the comments!
1. Changed the address tag to p tag for author name
2. I used the br element because time is an inline element and didn't want the time and cite element to display next to each other. Is there a better of displaying those 2 elements on different lines?
3. Will add span and use CSS to make it pop more 
4. Removed code tag

**Comment by mfehrenbach** [comment]
> * I used the br element because time is an inline element and didn't want the time and cite element to display next to each other. Is there a better of displaying those 2 elements on different lines?

Yep, you can set these to `display: block` in your CSS—or put them into other block containers (`p`, `div`, etc.)!
